from __future__ import annotations

from typing import Any, Dict, Optional
from uuid import uuid4

from fastapi import APIRouter, Depends, HTTPException

from app.core.security import get_current_user
from app.services.xml_generator import GoAMLGenerator

router = APIRouter(prefix="/reports")

_REPORTS: Dict[str, Dict[str, Any]] = {}
_generator = GoAMLGenerator()


@router.post("/str/generate")
async def generate_str(payload: Dict[str, Any], user: Dict[str, Any] = Depends(get_current_user)):
    alert_id = payload.get("alert_id")
    if not alert_id:
        raise HTTPException(status_code=400, detail="alert_id is required")
    report_id = str(uuid4())
    xml_preview = _generator.generate_str(
        reporting_entity={"name": "Demo Reporting Entity", "registration_number": "RC-000000"},
        suspicious_activity={"reason": "Auto-generated STR draft", "alert_id": alert_id},
        transactions=[],
        narrative="Draft STR generated by the AML platform.",
    )
    _REPORTS[report_id] = {"type": "STR", "status": "draft", "xml": xml_preview, "alert_id": alert_id}
    return {"report_id": report_id, "xml_preview": xml_preview, "validation_passed": True}


@router.post("/str/submit")
async def submit_str(payload: Dict[str, Any], user: Dict[str, Any] = Depends(get_current_user)):
    report_id = payload.get("report_id")
    if not report_id or report_id not in _REPORTS:
        raise HTTPException(status_code=404, detail="Report not found")
    _REPORTS[report_id]["status"] = "submitted"
    submission_id = str(uuid4())
    return {"submission_id": submission_id, "nfiu_reference": None}


@router.get("/str/{report_id}")
async def get_str(report_id: str, user: Dict[str, Any] = Depends(get_current_user)):
    r = _REPORTS.get(report_id)
    if not r or r.get("type") != "STR":
        raise HTTPException(status_code=404, detail="Report not found")
    return {"report_id": report_id, "status": r.get("status"), "xml_content": r.get("xml")}


@router.post("/str/{report_id}/regenerate")
async def regenerate_str(report_id: str, payload: Dict[str, Any], user: Dict[str, Any] = Depends(get_current_user)):
    r = _REPORTS.get(report_id)
    if not r:
        raise HTTPException(status_code=404, detail="Report not found")
    alert_id = r.get("alert_id")
    xml_preview = _generator.generate_str(
        reporting_entity={"name": "Demo Reporting Entity", "registration_number": "RC-000000"},
        suspicious_activity={"reason": "Regenerated STR draft", "alert_id": alert_id},
        transactions=[],
        narrative="Regenerated STR generated by the AML platform.",
    )
    r["xml"] = xml_preview
    r["status"] = "draft"
    return {"report_id": report_id, "xml_preview": xml_preview, "validation_passed": True}


@router.get("/str/")
async def list_strs(
    status: Optional[str] = None,
    user: Dict[str, Any] = Depends(get_current_user),
):
    items = []
    for rid, r in _REPORTS.items():
        if r.get("type") != "STR":
            continue
        if status and r.get("status") != status:
            continue
        items.append({"report_id": rid, "status": r.get("status"), "alert_id": r.get("alert_id")})
    return {"items": items, "total": len(items)}


@router.get("/compliance/dashboard")
async def compliance_dashboard(user: Dict[str, Any] = Depends(get_current_user)):
    return {
        "str_submission_rate": 0.0,
        "acceptance_rate": None,
        "average_time_to_submit_hours": None,
        "regulatory_deadlines": [],
    }


@router.post("/validate-xml")
async def validate_xml(payload: Dict[str, Any], user: Dict[str, Any] = Depends(get_current_user)):
    xml_content = payload.get("xml_content")
    if not xml_content:
        raise HTTPException(status_code=400, detail="xml_content is required")
    # Stub: only checks if it parses
    ok = xml_content.strip().startswith("<")
    return {"valid": ok, "errors": [] if ok else ["XML does not look valid"]}

