from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional
from uuid import uuid4

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import Response

from app.api.v1.alerts import _ALERTS
from app.api.v1.transactions import _TXNS
from app.core.security import get_current_user
from app.services.customer_kyc_db import get_or_create_customer_kyc
from app.services.str_word_generator import render_str_docx_bytes
from app.services.xml_generator import GoAMLGenerator

router = APIRouter(prefix="/reports")

_REPORTS: Dict[str, Dict[str, Any]] = {}
_generator = GoAMLGenerator()


def _compute_customer_cashflow_totals(customer_id: str) -> tuple[float, float]:
    # Lightweight cashflow approximation for STR narrative.
    inflow_types = {"salary", "transfer_in", "pos_settlement", "cash_deposit", "wire"}
    outflow_types = {"transfer_out"}
    inflows = 0.0
    outflows = 0.0
    for t in _TXNS.values():
        if t.customer_id != customer_id:
            continue
        tx_type = str(t.transaction_type or "").lower()
        if tx_type in inflow_types:
            inflows += float(t.amount or 0.0)
        elif tx_type in outflow_types:
            outflows += float(t.amount or 0.0)
    return inflows, outflows


@router.post("/str/generate")
async def generate_str(payload: Dict[str, Any], user: Dict[str, Any] = Depends(get_current_user)):
    alert_id = payload.get("alert_id")
    if not alert_id:
        raise HTTPException(status_code=400, detail="alert_id is required")

    alert = _ALERTS.get(alert_id)
    if not alert:
        raise HTTPException(status_code=404, detail="alert not found")

    txn = _TXNS.get(alert.transaction_id)
    txn_dict = (
        txn.model_dump()
        if txn
        else {
            "created_at": datetime.utcnow(),
            "amount": 0.0,
            "transaction_type": "",
            "currency": "NGN",
            "narrative": alert.summary,
            "metadata": {},
        }
    )

    inflows_total, outflows_total = _compute_customer_cashflow_totals(alert.customer_id)
    period_text = "January 1, 2025, to March 13, 2026"

    report_id = str(uuid4())
    xml_preview = _generator.generate_str(
        reporting_entity={"name": "Demo Reporting Entity", "registration_number": "RC-000000"},
        suspicious_activity={"reason": alert.summary or "Auto-generated STR draft", "alert_id": alert_id},
        transactions=[],
        narrative=(txn_dict.get("narrative") or "Draft STR generated by the AML platform.")[:1000],
    )

    alert_context = alert.model_dump()
    alert_context["inflows_total"] = inflows_total
    alert_context["outflows_total"] = outflows_total
    alert_context["period_text"] = period_text

    _REPORTS[report_id] = {
        "type": "STR",
        "status": "draft",
        "xml": xml_preview,
        "alert_id": alert_id,
        "customer_id": alert.customer_id,
        "txn": txn_dict,
        "alert": alert_context,
    }

    return {"report_id": report_id, "xml_preview": xml_preview, "validation_passed": True}


@router.post("/str/submit")
async def submit_str(payload: Dict[str, Any], user: Dict[str, Any] = Depends(get_current_user)):
    report_id = payload.get("report_id")
    if not report_id or report_id not in _REPORTS:
        raise HTTPException(status_code=404, detail="Report not found")
    _REPORTS[report_id]["status"] = "submitted"
    submission_id = str(uuid4())
    return {"submission_id": submission_id, "nfiu_reference": None}


@router.get("/str/{report_id}")
async def get_str(report_id: str, user: Dict[str, Any] = Depends(get_current_user)):
    r = _REPORTS.get(report_id)
    if not r or r.get("type") != "STR":
        raise HTTPException(status_code=404, detail="Report not found")
    return {"report_id": report_id, "status": r.get("status"), "xml_content": r.get("xml")}


@router.post("/str/{report_id}/regenerate")
async def regenerate_str(report_id: str, payload: Dict[str, Any], user: Dict[str, Any] = Depends(get_current_user)):
    r = _REPORTS.get(report_id)
    if not r:
        raise HTTPException(status_code=404, detail="Report not found")
    alert_id = r.get("alert_id")
    alert = _ALERTS.get(alert_id)
    if not alert:
        raise HTTPException(status_code=404, detail="alert not found")

    txn = _TXNS.get(alert.transaction_id)
    txn_dict = txn.model_dump() if txn else r.get("txn") or {}

    inflows_total, outflows_total = _compute_customer_cashflow_totals(alert.customer_id)
    period_text = "January 1, 2025, to March 13, 2026"

    xml_preview = _generator.generate_str(
        reporting_entity={"name": "Demo Reporting Entity", "registration_number": "RC-000000"},
        suspicious_activity={"reason": alert.summary or "Regenerated STR draft", "alert_id": alert_id},
        transactions=[],
        narrative=(txn_dict.get("narrative") or "Regenerated STR generated by the AML platform.")[:1000],
    )
    r["xml"] = xml_preview
    r["status"] = "draft"
    r["customer_id"] = alert.customer_id
    r["txn"] = txn_dict
    r["alert"] = {**alert.model_dump(), "inflows_total": inflows_total, "outflows_total": outflows_total, "period_text": period_text}
    return {"report_id": report_id, "xml_preview": xml_preview, "validation_passed": True}


def _approver_display_name(user: Dict[str, Any]) -> str:
    return (
        str(user.get("display_name") or "").strip()
        or str(user.get("name") or "").strip()
        or str(user.get("email") or "").strip()
        or str(user.get("sub") or "").strip()
        or "Authorized Officer"
    )


@router.get("/str/{report_id}/download")
async def download_str(
    request: Request,
    report_id: str,
    format: str = "word",
    user: Dict[str, Any] = Depends(get_current_user),
):
    r = _REPORTS.get(report_id)
    if not r or r.get("type") != "STR":
        raise HTTPException(status_code=404, detail="Report not found")

    fmt = format.lower().strip()
    if fmt not in {"word", "xml"}:
        raise HTTPException(status_code=400, detail="format must be 'word' or 'xml'")

    if fmt == "xml":
        xml_content = r.get("xml") or ""
        return Response(
            content=xml_content,
            media_type="application/xml",
            headers={"Content-Disposition": f'attachment; filename="STR_{report_id}.xml"'},
        )

    txn_dict = r.get("txn") or {}
    alert_context = r.get("alert") or {}
    customer_id = r.get("customer_id") or alert_context.get("customer_id") or ""
    pg = getattr(request.app.state, "pg", None)
    customer = await get_or_create_customer_kyc(pg, customer_id, txn_dict)
    doc_bytes = render_str_docx_bytes(
        customer=customer,
        txn=txn_dict,
        alert=alert_context,
        approver_name=_approver_display_name(user),
    )
    return Response(
        content=doc_bytes,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="STR_{report_id}.docx"'},
    )


@router.get("/str/")
async def list_strs(
    status: Optional[str] = None,
    user: Dict[str, Any] = Depends(get_current_user),
):
    items = []
    for rid, r in _REPORTS.items():
        if r.get("type") != "STR":
            continue
        if status and r.get("status") != status:
            continue
        items.append({"report_id": rid, "status": r.get("status"), "alert_id": r.get("alert_id")})
    return {"items": items, "total": len(items)}


@router.get("/compliance/dashboard")
async def compliance_dashboard(user: Dict[str, Any] = Depends(get_current_user)):
    return {
        "str_submission_rate": 0.0,
        "acceptance_rate": None,
        "average_time_to_submit_hours": None,
        "regulatory_deadlines": [],
    }


@router.post("/validate-xml")
async def validate_xml(payload: Dict[str, Any], user: Dict[str, Any] = Depends(get_current_user)):
    xml_content = payload.get("xml_content")
    if not xml_content:
        raise HTTPException(status_code=400, detail="xml_content is required")
    # Stub: only checks if it parses
    ok = xml_content.strip().startswith("<")
    return {"valid": ok, "errors": [] if ok else ["XML does not look valid"]}

